"""empty message

Revision ID: 445ede271902
Revises: 8f14e2230df0
Create Date: 2021-02-20 20:54:19.932899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '445ede271902'
down_revision = '8f14e2230df0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('file', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'file')
    # ### end Alembic commands ###
