"""empty message

Revision ID: 628fc182f32e
Revises: a1ac1414ef9f
Create Date: 2021-02-14 11:12:23.027289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '628fc182f32e'
down_revision = 'a1ac1414ef9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_active')
    # ### end Alembic commands ###
